version: '2'
services:
  web:
    image: odoo:14.0
    depends_on:
      - db
    ports:
      - "5000:8069"
    volumes:
      - demo_docker-web-data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./addons:/mnt/extra-addons
      - ./enterprise:/mnt/enterprise
  db:
    image: postgres:12
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - demo_docker-db-data:/var/lib/postgresql/data/pgdata
volumes:
  demo_docker-web-data:
  demo_docker-db-data:
